# Generated by Django 5.1.6 on 2025-02-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_customer_profilecomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='license_number',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
